name: Git checks
on: [pull_request]

jobs:
  git_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          architecture: "x64"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Initialize project
        run: pnpm i --frozen-lockfile
      - name: Run commitlint
        run: pnpm dlx commitlint --from=$(git rev-list "origin/${GITHUB_BASE_REF}"..HEAD | sed '1!d')~1
      - name: Ensure linear git history
        run: git merge-base --is-ancestor "origin/${GITHUB_BASE_REF}" HEAD
      - name: Check for fixup or WIP commits
        run: |
          ! git log "origin/${GITHUB_BASE_REF}..HEAD" | egrep ' fixup! |wip|Wip|WIP'
